export const PERMISSIONS = {
  CREATE_CASE: "CREATE_CASE",
  UPDATE_CASE: "UPDATE_CASE",
  DELETE_CASE: "DELETE_CASE",

  CREATE_LOAN: "CREATE_LOAN",
  CLOSE_LOAN: "CLOSE_LOAN",

  VIEW_REPORTS: "VIEW_REPORTS",

  EXPORT_REPORTS: "EXPORT_REPORTS",
} as const;